config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do 
    get "admins/users/list", to: "admins/sessions#list", as:"users_list"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :zombies do
    resources :brains
  end
  get '/sexto/cerebros', to: 'brains#index', as: 'brains'
  root to: 'zombies#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Zombies Rules" %></title>
<%= favicon_link_tag 'icofav.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Zombies App</li>
        <li>
          <% if user_signed_in? || admin_signed_in?%>
        <li>
          <%= link_to 'Home zombie', zombies_path %>
      <ul class="menu">
       
        <li>     
          <%= link_to 'Brains', brains_path %>
        </li>
      </ul>
        </li>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="top-bar-right"> 
    <% if user_signed_in? %> 
      Logged in as <strong><%= current_user.email %></strong>. 
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | 
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    <% elsif admin_signed_in? %> 
      Logged in as <strong><%= current_admin.email %></strong>. 
      <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> | 
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
    <% else %> 
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> | 
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %> 
    <% end %>
  </div>
  </div>
   <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>

  </body>
</html>